MAX_RECIPE_NAME_LENGTH = 150
MAX_RECIPE_TEXT_LENGTH = 800
MIN_COOKING_TIME = 1
MAX_TAG_NAME_LENGTH = 150
MAX_TAG_SLUG_LENGTH = 150
MAX_INGREDIENT_NAME_LENGTH = 150
MAX_MEASUREMENT_UNIT_LENGTH = 150
RECIPE_IMAGE_UPLOAD_PATH = 'recipes/images'
