USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 150
NAME_MAX_LENGTH = 150
PASSWORD_MAX_LENGTH = 150
USERNAME_VERBOSE = 'имя пользователя'
USERNAME_HELP = 'Обязательное поле'
EMAIL_VERBOSE = 'электронная почта'
EMAIL_HELP = 'обязательное поле'
FIRST_NAME_VERBOSE = 'настоящее имя пользователя'
FIRST_NAME_HELP = 'обязательное поле'
LAST_NAME_VERBOSE = 'Фамилия пользователя'
PASSWORD_VERBOSE = 'Пароль'
AVATAR_VERBOSE = 'Аватар пользователя'
AVATAR_HELP = 'вы можете загрузить отображаемое фото'
AVATAR_UPLOAD_TO = 'users/avatars'
USER_VERBOSE = 'пользователь'
USER_VERBOSE_PLURAL = 'пользователи'
FOLLOWER_UNIQUE_CONSTRAINT_NAME = 'me0'
FOLLOWER_CHECK_CONSTRAINT_NAME = 'me1'
