USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 150
NAME_MAX_LENGTH = 150
PASSWORD_MAX_LENGTH = 150

FOLLOWER_UNIQUE_CONSTRAINT_NAME = 'unique_follower'
FOLLOWER_SELF_FOLLOW_CONSTRAINT_NAME = 'prevent_self_follow'