# Generated by Django 4.2.16 on 2025-05-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeuser',
            name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='text',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('name',), 'verbose_name': 'Рецепт'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='created_at',
        ),
        migrations.DeleteModel(
            name='RecipeItself',
        ),
        migrations.DeleteModel(
            name='RecipeUser',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
