# Generated by Django 4.2.16 on 2025-05-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_options_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeuser',
            name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='text',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='username',
        ),
        migrations.DeleteModel(
            name='RecipeItself',
        ),
        migrations.DeleteModel(
            name='RecipeUser',
        ),
    ]
