# Generated by Django 4.2.16 on 2025-05-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipeitself_recipeuser_shoppinglist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeItself',
        ),
    ]
