# Generated by Django 4.2.16 on 2025-05-24 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_alter_recipeingredient_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeItself',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='unique_recipe_ingredient',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='recipeitself',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User.email+', to=settings.AUTH_USER_MODEL, verbose_name='email пользователя'),
        ),
        migrations.AddField(
            model_name='recipeitself',
            name='first_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User.first_name+', to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='recipeitself',
            name='last_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User.last_name+', to=settings.AUTH_USER_MODEL, verbose_name='Фамилия пользователя'),
        ),
        migrations.AddField(
            model_name='recipeitself',
            name='measurement_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ingredient.mu+', to='recipes.ingredient', verbose_name='Единицы измерения'),
        ),
        migrations.AddField(
            model_name='recipeitself',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipe.name+', to='recipes.recipe', verbose_name='Имя рецепта'),
        ),
        migrations.AddField(
            model_name='recipeitself',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User.password+', to=settings.AUTH_USER_MODEL, verbose_name='Пароль'),
        ),
        migrations.AddField(
            model_name='recipeitself',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipe.text+', to='recipes.recipe', verbose_name='Текст рецепта'),
        ),
        migrations.AddField(
            model_name='recipeitself',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User.username+', to=settings.AUTH_USER_MODEL, verbose_name='Никнейм пользователя'),
        ),
    ]
